// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: app/interaction/rpc/interaction.proto

package interaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 点赞相关 ---
type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_app_interaction_rpc_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_interaction_rpc_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_app_interaction_rpc_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type LikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	mi := &file_app_interaction_rpc_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_interaction_rpc_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_app_interaction_rpc_interaction_proto_rawDescGZIP(), []int{1}
}

// --- 评论相关 ---
type CommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentRequest) Reset() {
	*x = CommentRequest{}
	mi := &file_app_interaction_rpc_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequest) ProtoMessage() {}

func (x *CommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_interaction_rpc_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequest.ProtoReflect.Descriptor instead.
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return file_app_interaction_rpc_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *CommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 返回生成的评论ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_app_interaction_rpc_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_interaction_rpc_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_app_interaction_rpc_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *CommentResponse) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

var File_app_interaction_rpc_interaction_proto protoreflect.FileDescriptor

const file_app_interaction_rpc_interaction_proto_rawDesc = "" +
	"\n" +
	"%app/interaction/rpc/interaction.proto\x12\vinteraction\"?\n" +
	"\vLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\"\x0e\n" +
	"\fLikeResponse\"\\\n" +
	"\x0eCommentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"0\n" +
	"\x0fCommentResponse\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId2\x90\x01\n" +
	"\vInteraction\x12;\n" +
	"\x04Like\x12\x18.interaction.LikeRequest\x1a\x19.interaction.LikeResponse\x12D\n" +
	"\aComment\x12\x1b.interaction.CommentRequest\x1a\x1c.interaction.CommentResponseB\x0fZ\r./interactionb\x06proto3"

var (
	file_app_interaction_rpc_interaction_proto_rawDescOnce sync.Once
	file_app_interaction_rpc_interaction_proto_rawDescData []byte
)

func file_app_interaction_rpc_interaction_proto_rawDescGZIP() []byte {
	file_app_interaction_rpc_interaction_proto_rawDescOnce.Do(func() {
		file_app_interaction_rpc_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_interaction_rpc_interaction_proto_rawDesc), len(file_app_interaction_rpc_interaction_proto_rawDesc)))
	})
	return file_app_interaction_rpc_interaction_proto_rawDescData
}

var file_app_interaction_rpc_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_interaction_rpc_interaction_proto_goTypes = []any{
	(*LikeRequest)(nil),     // 0: interaction.LikeRequest
	(*LikeResponse)(nil),    // 1: interaction.LikeResponse
	(*CommentRequest)(nil),  // 2: interaction.CommentRequest
	(*CommentResponse)(nil), // 3: interaction.CommentResponse
}
var file_app_interaction_rpc_interaction_proto_depIdxs = []int32{
	0, // 0: interaction.Interaction.Like:input_type -> interaction.LikeRequest
	2, // 1: interaction.Interaction.Comment:input_type -> interaction.CommentRequest
	1, // 2: interaction.Interaction.Like:output_type -> interaction.LikeResponse
	3, // 3: interaction.Interaction.Comment:output_type -> interaction.CommentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_interaction_rpc_interaction_proto_init() }
func file_app_interaction_rpc_interaction_proto_init() {
	if File_app_interaction_rpc_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_interaction_rpc_interaction_proto_rawDesc), len(file_app_interaction_rpc_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_interaction_rpc_interaction_proto_goTypes,
		DependencyIndexes: file_app_interaction_rpc_interaction_proto_depIdxs,
		MessageInfos:      file_app_interaction_rpc_interaction_proto_msgTypes,
	}.Build()
	File_app_interaction_rpc_interaction_proto = out.File
	file_app_interaction_rpc_interaction_proto_goTypes = nil
	file_app_interaction_rpc_interaction_proto_depIdxs = nil
}
