// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: relation.proto

package relation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`    // 谁在关注
	FollowingId   int64                  `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // 关注了谁
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowReq) Reset() {
	*x = FollowReq{}
	mi := &file_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowReq) ProtoMessage() {}

func (x *FollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowReq.ProtoReflect.Descriptor instead.
func (*FollowReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{0}
}

func (x *FollowReq) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowReq) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type FollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResp) Reset() {
	*x = FollowResp{}
	mi := &file_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResp) ProtoMessage() {}

func (x *FollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResp.ProtoReflect.Descriptor instead.
func (*FollowResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{1}
}

type UnfollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   int64                  `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowReq) Reset() {
	*x = UnfollowReq{}
	mi := &file_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowReq) ProtoMessage() {}

func (x *UnfollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowReq.ProtoReflect.Descriptor instead.
func (*UnfollowReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowReq) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *UnfollowReq) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type UnfollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResp) Reset() {
	*x = UnfollowResp{}
	mi := &file_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResp) ProtoMessage() {}

func (x *UnfollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResp.ProtoReflect.Descriptor instead.
func (*UnfollowResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{3}
}

// 为了个人主页聚合 (选项C) 准备的核心接口：查询关注数和粉丝数
type RelationCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationCountReq) Reset() {
	*x = RelationCountReq{}
	mi := &file_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationCountReq) ProtoMessage() {}

func (x *RelationCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationCountReq.ProtoReflect.Descriptor instead.
func (*RelationCountReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{4}
}

func (x *RelationCountReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type RelationCountResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowingCount int64                  `protobuf:"varint,1,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"` // 关注了多少人
	FollowerCount  int64                  `protobuf:"varint,2,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`    // 有多少粉丝
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelationCountResp) Reset() {
	*x = RelationCountResp{}
	mi := &file_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationCountResp) ProtoMessage() {}

func (x *RelationCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationCountResp.ProtoReflect.Descriptor instead.
func (*RelationCountResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{5}
}

func (x *RelationCountResp) GetFollowingCount() int64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *RelationCountResp) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

// 检查是否已关注 (供前端按钮高亮使用)
type CheckIsFollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId int64                  `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	TargetUserId  int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIsFollowReq) Reset() {
	*x = CheckIsFollowReq{}
	mi := &file_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsFollowReq) ProtoMessage() {}

func (x *CheckIsFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsFollowReq.ProtoReflect.Descriptor instead.
func (*CheckIsFollowReq) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{6}
}

func (x *CheckIsFollowReq) GetCurrentUserId() int64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *CheckIsFollowReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type CheckIsFollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollow      bool                   `protobuf:"varint,1,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIsFollowResp) Reset() {
	*x = CheckIsFollowResp{}
	mi := &file_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsFollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsFollowResp) ProtoMessage() {}

func (x *CheckIsFollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsFollowResp.ProtoReflect.Descriptor instead.
func (*CheckIsFollowResp) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{7}
}

func (x *CheckIsFollowResp) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

var File_relation_proto protoreflect.FileDescriptor

const file_relation_proto_rawDesc = "" +
	"\n" +
	"\x0erelation.proto\x12\brelation\"O\n" +
	"\tFollowReq\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x03R\vfollowingId\"\f\n" +
	"\n" +
	"FollowResp\"Q\n" +
	"\vUnfollowReq\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x03R\vfollowingId\"\x0e\n" +
	"\fUnfollowResp\"8\n" +
	"\x10RelationCountReq\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\"c\n" +
	"\x11RelationCountResp\x12'\n" +
	"\x0ffollowing_count\x18\x01 \x01(\x03R\x0efollowingCount\x12%\n" +
	"\x0efollower_count\x18\x02 \x01(\x03R\rfollowerCount\"`\n" +
	"\x10CheckIsFollowReq\x12&\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\x03R\rcurrentUserId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"0\n" +
	"\x11CheckIsFollowResp\x12\x1b\n" +
	"\tis_follow\x18\x01 \x01(\bR\bisFollow2\x91\x02\n" +
	"\bRelation\x123\n" +
	"\x06Follow\x12\x13.relation.FollowReq\x1a\x14.relation.FollowResp\x129\n" +
	"\bUnfollow\x12\x15.relation.UnfollowReq\x1a\x16.relation.UnfollowResp\x12K\n" +
	"\x10GetRelationCount\x12\x1a.relation.RelationCountReq\x1a\x1b.relation.RelationCountResp\x12H\n" +
	"\rCheckIsFollow\x12\x1a.relation.CheckIsFollowReq\x1a\x1b.relation.CheckIsFollowRespB\fZ\n" +
	"./relationb\x06proto3"

var (
	file_relation_proto_rawDescOnce sync.Once
	file_relation_proto_rawDescData []byte
)

func file_relation_proto_rawDescGZIP() []byte {
	file_relation_proto_rawDescOnce.Do(func() {
		file_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)))
	})
	return file_relation_proto_rawDescData
}

var file_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_relation_proto_goTypes = []any{
	(*FollowReq)(nil),         // 0: relation.FollowReq
	(*FollowResp)(nil),        // 1: relation.FollowResp
	(*UnfollowReq)(nil),       // 2: relation.UnfollowReq
	(*UnfollowResp)(nil),      // 3: relation.UnfollowResp
	(*RelationCountReq)(nil),  // 4: relation.RelationCountReq
	(*RelationCountResp)(nil), // 5: relation.RelationCountResp
	(*CheckIsFollowReq)(nil),  // 6: relation.CheckIsFollowReq
	(*CheckIsFollowResp)(nil), // 7: relation.CheckIsFollowResp
}
var file_relation_proto_depIdxs = []int32{
	0, // 0: relation.Relation.Follow:input_type -> relation.FollowReq
	2, // 1: relation.Relation.Unfollow:input_type -> relation.UnfollowReq
	4, // 2: relation.Relation.GetRelationCount:input_type -> relation.RelationCountReq
	6, // 3: relation.Relation.CheckIsFollow:input_type -> relation.CheckIsFollowReq
	1, // 4: relation.Relation.Follow:output_type -> relation.FollowResp
	3, // 5: relation.Relation.Unfollow:output_type -> relation.UnfollowResp
	5, // 6: relation.Relation.GetRelationCount:output_type -> relation.RelationCountResp
	7, // 7: relation.Relation.CheckIsFollow:output_type -> relation.CheckIsFollowResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relation_proto_init() }
func file_relation_proto_init() {
	if File_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relation_proto_goTypes,
		DependencyIndexes: file_relation_proto_depIdxs,
		MessageInfos:      file_relation_proto_msgTypes,
	}.Build()
	File_relation_proto = out.File
	file_relation_proto_goTypes = nil
	file_relation_proto_depIdxs = nil
}
