// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type NoticeItem struct {
	Id         int64 `json:"id"`
	ActorId    int64 `json:"actorId"` // 谁操作的
	PostId     int64 `json:"postId"`  // 哪篇博文
	Type       int   `json:"type"`    // 1-点赞 2-评论
	IsRead     int   `json:"isRead"`
	CreateTime int64 `json:"createTime"`
}

type NoticeListReq struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type NoticeListResp struct {
	List  []NoticeItem `json:"list"`
	Total int64        `json:"total"`
}
