// Code generated by goctl. DO NOT EDIT.
package types

type NoticeItem struct {
	Id         int64 `json:"id,string"`
	ActorId    int64 `json:"actorId,string"` // 谁操作的
	PostId     int64 `json:"postId,string"`  // 哪篇博文
	Type       int   `json:"type"`           // 1-点赞 2-评论
	IsRead     int   `json:"isRead"`
	CreateTime int64 `json:"createTime"`
}

type NoticeListReq struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type NoticeListResp struct {
	List  []NoticeItem `json:"list"`
	Total int64        `json:"total"`
}

type ReadAllReq struct {
}

type ReadAllResp struct {
}

type ReadReq struct {
	NoticeId int64 `json:"notice_id,string"` // 前端传来的目标通知ID
}

type ReadResp struct {
}
