// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postFieldNames          = builder.RawFieldNames(&Post{})
	postRows                = strings.Join(postFieldNames, ",")
	postRowsExpectAutoSet   = strings.Join(stringx.Remove(postFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postRowsWithPlaceHolder = strings.Join(stringx.Remove(postFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePostIdPrefix = "cache:post:id:"
)

type (
	postModel interface {
		Insert(ctx context.Context, data *Post) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Post, error)
		Update(ctx context.Context, data *Post) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPostModel struct {
		sqlc.CachedConn
		table string
	}

	Post struct {
		Id           int64     `db:"id"`            // 全局唯一博文ID
		UserId       int64     `db:"user_id"`       // 作者ID (未来的分库分表 Sharding Key)
		Content      string    `db:"content"`       // 博文内容
		LikeCount    int64     `db:"like_count"`    // 点赞数
		CommentCount int64     `db:"comment_count"` // 评论数
		CreateTime   time.Time `db:"create_time"`   // 发布时间
		UpdateTime   time.Time `db:"update_time"`   // 更新时间
	}
)

func newPostModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPostModel {
	return &defaultPostModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`post`",
	}
}

func (m *defaultPostModel) Delete(ctx context.Context, id int64) error {
	postIdKey := fmt.Sprintf("%s%v", cachePostIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, postIdKey)
	return err
}

func (m *defaultPostModel) FindOne(ctx context.Context, id int64) (*Post, error) {
	postIdKey := fmt.Sprintf("%s%v", cachePostIdPrefix, id)
	var resp Post
	err := m.QueryRowCtx(ctx, &resp, postIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostModel) Insert(ctx context.Context, data *Post) (sql.Result, error) {
	postIdKey := fmt.Sprintf("%s%v", cachePostIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, postRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Content, data.LikeCount, data.CommentCount)
	}, postIdKey)
	return ret, err
}

func (m *defaultPostModel) Update(ctx context.Context, data *Post) error {
	postIdKey := fmt.Sprintf("%s%v", cachePostIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Content, data.LikeCount, data.CommentCount, data.Id)
	}, postIdKey)
	return err
}

func (m *defaultPostModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePostIdPrefix, primary)
}

func (m *defaultPostModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPostModel) tableName() string {
	return m.table
}
