// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: relation.proto

package server

import (
	"context"

	"miniblog/app/relation/rpc/internal/logic"
	"miniblog/app/relation/rpc/internal/svc"
	"miniblog/app/relation/rpc/relation"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServer) Follow(ctx context.Context, in *relation.FollowReq) (*relation.FollowResp, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *RelationServer) Unfollow(ctx context.Context, in *relation.UnfollowReq) (*relation.UnfollowResp, error) {
	l := logic.NewUnfollowLogic(ctx, s.svcCtx)
	return l.Unfollow(in)
}

func (s *RelationServer) GetRelationCount(ctx context.Context, in *relation.RelationCountReq) (*relation.RelationCountResp, error) {
	l := logic.NewGetRelationCountLogic(ctx, s.svcCtx)
	return l.GetRelationCount(in)
}

func (s *RelationServer) CheckIsFollow(ctx context.Context, in *relation.CheckIsFollowReq) (*relation.CheckIsFollowResp, error) {
	l := logic.NewCheckIsFollowLogic(ctx, s.svcCtx)
	return l.CheckIsFollow(in)
}
