// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	noticeFieldNames          = builder.RawFieldNames(&Notice{})
	noticeRows                = strings.Join(noticeFieldNames, ",")
	noticeRowsExpectAutoSet   = strings.Join(stringx.Remove(noticeFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	noticeRowsWithPlaceHolder = strings.Join(stringx.Remove(noticeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMiniblogDbNoticeIdPrefix = "cache:miniblogDb:notice:id:"
)

type (
	noticeModel interface {
		Insert(ctx context.Context, data *Notice) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Notice, error)
		Update(ctx context.Context, data *Notice) error
		Delete(ctx context.Context, id int64) error
	}

	defaultNoticeModel struct {
		sqlc.CachedConn
		table string
	}

	Notice struct {
		Id         int64     `db:"id"`       // 雪花算法ID
		UserId     int64     `db:"user_id"`  // 接收通知的用户ID（比如博文作者）
		ActorId    int64     `db:"actor_id"` // 触发动作的用户ID（比如点赞的人）
		PostId     int64     `db:"post_id"`  // 关联的博文ID
		Type       int64     `db:"type"`     // 通知类型: 1-被点赞, 2-被评论
		IsRead     int64     `db:"is_read"`  // 状态: 0-未读, 1-已读
		CreateTime time.Time `db:"create_time"`
	}
)

func newNoticeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNoticeModel {
	return &defaultNoticeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`notice`",
	}
}

func (m *defaultNoticeModel) Delete(ctx context.Context, id int64) error {
	miniblogDbNoticeIdKey := fmt.Sprintf("%s%v", cacheMiniblogDbNoticeIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, miniblogDbNoticeIdKey)
	return err
}

func (m *defaultNoticeModel) FindOne(ctx context.Context, id int64) (*Notice, error) {
	miniblogDbNoticeIdKey := fmt.Sprintf("%s%v", cacheMiniblogDbNoticeIdPrefix, id)
	var resp Notice
	err := m.QueryRowCtx(ctx, &resp, miniblogDbNoticeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", noticeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoticeModel) Insert(ctx context.Context, data *Notice) (sql.Result, error) {
	miniblogDbNoticeIdKey := fmt.Sprintf("%s%v", cacheMiniblogDbNoticeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, noticeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.ActorId, data.PostId, data.Type, data.IsRead)
	}, miniblogDbNoticeIdKey)
	return ret, err
}

func (m *defaultNoticeModel) Update(ctx context.Context, data *Notice) error {
	miniblogDbNoticeIdKey := fmt.Sprintf("%s%v", cacheMiniblogDbNoticeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, noticeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.ActorId, data.PostId, data.Type, data.IsRead, data.Id)
	}, miniblogDbNoticeIdKey)
	return err
}

func (m *defaultNoticeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMiniblogDbNoticeIdPrefix, primary)
}

func (m *defaultNoticeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", noticeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNoticeModel) tableName() string {
	return m.table
}
