// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: post.proto

package server

import (
	"context"

	"miniblog/app/post/rpc/internal/logic"
	"miniblog/app/post/rpc/internal/svc"
	"miniblog/app/post/rpc/post"
)

type PostServer struct {
	svcCtx *svc.ServiceContext
	post.UnimplementedPostServer
}

func NewPostServer(svcCtx *svc.ServiceContext) *PostServer {
	return &PostServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServer) Publish(ctx context.Context, in *post.PublishRequest) (*post.PublishResponse, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

// 内部获取列表的 RPC 方法
func (s *PostServer) List(ctx context.Context, in *post.ListRequest) (*post.ListResponse, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

// 新增：详情和删除 RPC 方法
func (s *PostServer) Detail(ctx context.Context, in *post.DetailRequest) (*post.DetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

func (s *PostServer) Delete(ctx context.Context, in *post.DeleteRequest) (*post.DeleteResponse, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
