// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FollowReq struct {
	TargetUserId int64 `json:"targetUserId"`
}

type FollowResp struct {
}

type UnfollowReq struct {
	TargetUserId int64 `json:"targetUserId"`
}

type UnfollowResp struct {
}
