// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ListReq struct {
	Page     int64 `json:"page"`     // 第几页
	PageSize int64 `json:"pageSize"` // 每页多少条
}

type ListResp struct {
	List  []PostItem `json:"list"`  // 博文数组
	Total int64      `json:"total"` // 总条数
}

type PostItem struct {
	Id       int64  `json:"id,string"`     // 【加 ,string】
	UserId   int64  `json:"userId,string"` // 【加 ,string】
	Content  string `json:"content"`
	CreateAt string `json:"createAt"` // 返回友好的时间格式
}

type PublishReq struct {
	Content string `json:"content"`
}

type PublishResp struct {
	PostId int64 `json:"post_id,string"` // 【加 ,string】
}
