// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DeleteReq struct {
	PostId int64 `json:"post_id"`
}

type DeleteResp struct {
}

type DetailReq struct {
	PostId int64 `json:"post_id"`
}

type DetailResp struct {
	Post PostItem `json:"post"`
}

type ListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type ListResp struct {
	List  []PostItem `json:"list"`
	Total int64      `json:"total"`
}

type PostItem struct {
	Id           int64    `json:"id"`
	UserId       int64    `json:"userId"`
	AuthorName   string   `json:"authorName"`
	AuthorAvatar string   `json:"authorAvatar"`
	Content      string   `json:"content"`
	Images       []string `json:"images"`
	LikeCount    int64    `json:"like_count"`
	CommentCount int64    `json:"comment_count"`
	IsLiked      bool     `json:"is_liked"`
	CreateAt     string   `json:"createAt"`
}

type PublishReq struct {
	Content string   `json:"content"`
	Images  []string `json:"images,optional"`
}

type PublishResp struct {
	PostId int64 `json:"postId"`
}
