// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DeleteReq struct {
	PostId int64 `json:"post_id"`
}

type DeleteResp struct {
}

type DetailReq struct {
	PostId int64 `json:"post_id"`
}

type DetailResp struct {
	Post PostItem `json:"post"`
}

type ListReq struct {
	Page     int64 `json:"page"`     // 第几页
	PageSize int64 `json:"pageSize"` // 每页多少条
}

type ListResp struct {
	List  []PostItem `json:"list"`  // 博文数组
	Total int64      `json:"total"` // 总条数
}

type PostItem struct {
	Id           int64    `json:"id"`
	UserId       int64    `json:"userId"`
	Content      string   `json:"content"`
	Images       []string `json:"images"`        // 新增：博文图片
	LikeCount    int64    `json:"like_count"`    // 【网关新增】
	CommentCount int64    `json:"comment_count"` // 【网关新增】
	CreateAt     string   `json:"createAt"`      // 返回友好的时间格式
}

type PublishReq struct {
	Content string   `json:"content"`
	Images  []string `json:"images,optional"` // 新增：支持多张图片链接
}

type PublishResp struct {
	PostId int64 `json:"postId"`
}
