// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: relation.proto

package relationclient

import (
	"context"

	"miniblog/app/relation/rpc/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckIsFollowReq  = relation.CheckIsFollowReq
	CheckIsFollowResp = relation.CheckIsFollowResp
	FollowReq         = relation.FollowReq
	FollowResp        = relation.FollowResp
	RelationCountReq  = relation.RelationCountReq
	RelationCountResp = relation.RelationCountResp
	UnfollowReq       = relation.UnfollowReq
	UnfollowResp      = relation.UnfollowResp

	Relation interface {
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
		GetRelationCount(ctx context.Context, in *RelationCountReq, opts ...grpc.CallOption) (*RelationCountResp, error)
		CheckIsFollow(ctx context.Context, in *CheckIsFollowReq, opts ...grpc.CallOption) (*CheckIsFollowResp, error)
	}

	defaultRelation struct {
		cli zrpc.Client
	}
)

func NewRelation(cli zrpc.Client) Relation {
	return &defaultRelation{
		cli: cli,
	}
}

func (m *defaultRelation) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultRelation) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.Unfollow(ctx, in, opts...)
}

func (m *defaultRelation) GetRelationCount(ctx context.Context, in *RelationCountReq, opts ...grpc.CallOption) (*RelationCountResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.GetRelationCount(ctx, in, opts...)
}

func (m *defaultRelation) CheckIsFollow(ctx context.Context, in *CheckIsFollowReq, opts ...grpc.CallOption) (*CheckIsFollowResp, error) {
	client := relation.NewRelationClient(m.cli.Conn())
	return client.CheckIsFollow(ctx, in, opts...)
}
