version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: miniblog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miniblog_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    container_name: miniblog-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  minio:
    image: minio/minio
    container_name: miniblog-minio
    ports:
      - "9000:9000" # MinIO API 端口 (后端代码和服务通信用这个)
      - "9001:9001" # MinIO Console Web 控制台端口 (浏览器管理面板)
    environment:
      MINIO_ROOT_USER: admin           # 超级管理员账号
      MINIO_ROOT_PASSWORD: password123 # 超级管理员密码 (需大于8位)
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data