// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type PresignedUrlReq struct {
	Type    int    `json:"type"`
	FileExt string `json:"fileExt"`
}

type PresignedUrlResp struct {
	UploadUrl   string `json:"uploadUrl"`
	DownloadUrl string `json:"downloadUrl"`
}
