// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notice.proto

package server

import (
	"context"

	"miniblog/app/notice/rpc/internal/logic"
	"miniblog/app/notice/rpc/internal/svc"
	"miniblog/app/notice/rpc/notice"
)

type NoticeRpcServer struct {
	svcCtx *svc.ServiceContext
	notice.UnimplementedNoticeRpcServer
}

func NewNoticeRpcServer(svcCtx *svc.ServiceContext) *NoticeRpcServer {
	return &NoticeRpcServer{
		svcCtx: svcCtx,
	}
}

// 内部接口：供 Interaction 服务异步调用来生成通知
func (s *NoticeRpcServer) CreateNotice(ctx context.Context, in *notice.CreateNoticeReq) (*notice.CreateNoticeResp, error) {
	l := logic.NewCreateNoticeLogic(ctx, s.svcCtx)
	return l.CreateNotice(in)
}
