// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"miniblog/app/interaction/rpc/interaction"
	"miniblog/app/interaction/rpc/internal/logic"
	"miniblog/app/interaction/rpc/internal/svc"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServer) Like(ctx context.Context, in *interaction.LikeRequest) (*interaction.LikeResponse, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

func (s *InteractionServer) Unlike(ctx context.Context, in *interaction.UnlikeRequest) (*interaction.UnlikeResponse, error) {
	l := logic.NewUnlikeLogic(ctx, s.svcCtx)
	return l.Unlike(in)
}

func (s *InteractionServer) Comment(ctx context.Context, in *interaction.CommentRequest) (*interaction.CommentResponse, error) {
	l := logic.NewCommentLogic(ctx, s.svcCtx)
	return l.Comment(in)
}

func (s *InteractionServer) CommentDelete(ctx context.Context, in *interaction.CommentDeleteRequest) (*interaction.CommentDeleteResponse, error) {
	l := logic.NewCommentDeleteLogic(ctx, s.svcCtx)
	return l.CommentDelete(in)
}

func (s *InteractionServer) CommentList(ctx context.Context, in *interaction.CommentListRequest) (*interaction.CommentListResponse, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}

func (s *InteractionServer) LikedList(ctx context.Context, in *interaction.LikedListRequest) (*interaction.LikedListResponse, error) {
	l := logic.NewLikedListLogic(ctx, s.svcCtx)
	return l.LikedList(in)
}
