// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.9
// source: app/notice/rpc/notice.proto

package notice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoticeRpc_CreateNotice_FullMethodName = "/notice.NoticeRpc/CreateNotice"
)

// NoticeRpcClient is the client API for NoticeRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoticeRpcClient interface {
	// 内部接口：供 Interaction 服务异步调用来生成通知
	CreateNotice(ctx context.Context, in *CreateNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error)
}

type noticeRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewNoticeRpcClient(cc grpc.ClientConnInterface) NoticeRpcClient {
	return &noticeRpcClient{cc}
}

func (c *noticeRpcClient) CreateNotice(ctx context.Context, in *CreateNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNoticeResp)
	err := c.cc.Invoke(ctx, NoticeRpc_CreateNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoticeRpcServer is the server API for NoticeRpc service.
// All implementations must embed UnimplementedNoticeRpcServer
// for forward compatibility.
type NoticeRpcServer interface {
	// 内部接口：供 Interaction 服务异步调用来生成通知
	CreateNotice(context.Context, *CreateNoticeReq) (*CreateNoticeResp, error)
	mustEmbedUnimplementedNoticeRpcServer()
}

// UnimplementedNoticeRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoticeRpcServer struct{}

func (UnimplementedNoticeRpcServer) CreateNotice(context.Context, *CreateNoticeReq) (*CreateNoticeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNotice not implemented")
}
func (UnimplementedNoticeRpcServer) mustEmbedUnimplementedNoticeRpcServer() {}
func (UnimplementedNoticeRpcServer) testEmbeddedByValue()                   {}

// UnsafeNoticeRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoticeRpcServer will
// result in compilation errors.
type UnsafeNoticeRpcServer interface {
	mustEmbedUnimplementedNoticeRpcServer()
}

func RegisterNoticeRpcServer(s grpc.ServiceRegistrar, srv NoticeRpcServer) {
	// If the following call panics, it indicates UnimplementedNoticeRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoticeRpc_ServiceDesc, srv)
}

func _NoticeRpc_CreateNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeRpcServer).CreateNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeRpc_CreateNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeRpcServer).CreateNotice(ctx, req.(*CreateNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NoticeRpc_ServiceDesc is the grpc.ServiceDesc for NoticeRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoticeRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notice.NoticeRpc",
	HandlerType: (*NoticeRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotice",
			Handler:    _NoticeRpc_CreateNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/notice/rpc/notice.proto",
}
