// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: app/notice/rpc/notice.proto

package notice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 互动服务传过来的生成通知请求
type CreateNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 接收方ID
	ActorId       int64                  `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // 操作方ID
	PostId        int64                  `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`    // 目标博文ID
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                      // 类型(1点赞 2评论)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoticeReq) Reset() {
	*x = CreateNoticeReq{}
	mi := &file_app_notice_rpc_notice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoticeReq) ProtoMessage() {}

func (x *CreateNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_notice_rpc_notice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoticeReq.ProtoReflect.Descriptor instead.
func (*CreateNoticeReq) Descriptor() ([]byte, []int) {
	return file_app_notice_rpc_notice_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNoticeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNoticeReq) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *CreateNoticeReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateNoticeReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CreateNoticeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoticeResp) Reset() {
	*x = CreateNoticeResp{}
	mi := &file_app_notice_rpc_notice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoticeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoticeResp) ProtoMessage() {}

func (x *CreateNoticeResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_notice_rpc_notice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoticeResp.ProtoReflect.Descriptor instead.
func (*CreateNoticeResp) Descriptor() ([]byte, []int) {
	return file_app_notice_rpc_notice_proto_rawDescGZIP(), []int{1}
}

var File_app_notice_rpc_notice_proto protoreflect.FileDescriptor

const file_app_notice_rpc_notice_proto_rawDesc = "" +
	"\n" +
	"\x1bapp/notice/rpc/notice.proto\x12\x06notice\"r\n" +
	"\x0fCreateNoticeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\x03R\aactorId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x03R\x06postId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\"\x12\n" +
	"\x10CreateNoticeResp2N\n" +
	"\tNoticeRpc\x12A\n" +
	"\fCreateNotice\x12\x17.notice.CreateNoticeReq\x1a\x18.notice.CreateNoticeRespB\n" +
	"Z\b./noticeb\x06proto3"

var (
	file_app_notice_rpc_notice_proto_rawDescOnce sync.Once
	file_app_notice_rpc_notice_proto_rawDescData []byte
)

func file_app_notice_rpc_notice_proto_rawDescGZIP() []byte {
	file_app_notice_rpc_notice_proto_rawDescOnce.Do(func() {
		file_app_notice_rpc_notice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_notice_rpc_notice_proto_rawDesc), len(file_app_notice_rpc_notice_proto_rawDesc)))
	})
	return file_app_notice_rpc_notice_proto_rawDescData
}

var file_app_notice_rpc_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_notice_rpc_notice_proto_goTypes = []any{
	(*CreateNoticeReq)(nil),  // 0: notice.CreateNoticeReq
	(*CreateNoticeResp)(nil), // 1: notice.CreateNoticeResp
}
var file_app_notice_rpc_notice_proto_depIdxs = []int32{
	0, // 0: notice.NoticeRpc.CreateNotice:input_type -> notice.CreateNoticeReq
	1, // 1: notice.NoticeRpc.CreateNotice:output_type -> notice.CreateNoticeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_notice_rpc_notice_proto_init() }
func file_app_notice_rpc_notice_proto_init() {
	if File_app_notice_rpc_notice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_notice_rpc_notice_proto_rawDesc), len(file_app_notice_rpc_notice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_notice_rpc_notice_proto_goTypes,
		DependencyIndexes: file_app_notice_rpc_notice_proto_depIdxs,
		MessageInfos:      file_app_notice_rpc_notice_proto_msgTypes,
	}.Build()
	File_app_notice_rpc_notice_proto = out.File
	file_app_notice_rpc_notice_proto_goTypes = nil
	file_app_notice_rpc_notice_proto_depIdxs = nil
}
