// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"miniblog/app/interaction/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取博文的评论列表
				Method:  http.MethodPost,
				Path:    "/comment/list",
				Handler: CommentListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/interaction"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 发表评论
				Method:  http.MethodPost,
				Path:    "/comment",
				Handler: CommentHandler(serverCtx),
			},
			{
				// 点赞
				Method:  http.MethodPost,
				Path:    "/like",
				Handler: LikeHandler(serverCtx),
			},
			{
				// 获取当前用户点赞过的博文ID列表
				Method:  http.MethodPost,
				Path:    "/like/list",
				Handler: LikedListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/interaction"),
	)
}
