// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notice.proto

package noticerpc

import (
	"context"

	"miniblog/app/notice/rpc/notice"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateNoticeReq  = notice.CreateNoticeReq
	CreateNoticeResp = notice.CreateNoticeResp

	NoticeRpc interface {
		// 内部接口：供 Interaction 服务异步调用来生成通知
		CreateNotice(ctx context.Context, in *CreateNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error)
	}

	defaultNoticeRpc struct {
		cli zrpc.Client
	}
)

func NewNoticeRpc(cli zrpc.Client) NoticeRpc {
	return &defaultNoticeRpc{
		cli: cli,
	}
}

// 内部接口：供 Interaction 服务异步调用来生成通知
func (m *defaultNoticeRpc) CreateNotice(ctx context.Context, in *CreateNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error) {
	client := notice.NewNoticeRpcClient(m.cli.Conn())
	return client.CreateNotice(ctx, in, opts...)
}
