// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	UserId int64 `json:"userId"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
}

type UserProfileReq struct {
	TargetUserId int64 `json:"targetUserId"` // 你想看谁的主页
}

type UserProfileResp struct {
	UserId         int64  `json:"userId"`
	Username       string `json:"username"`
	Avatar         string `json:"avatar"`
	Bio            string `json:"bio"`
	FollowingCount int64  `json:"followingCount"` // 关注了多少人
	FollowerCount  int64  `json:"followerCount"`  // 有多少粉丝
	IsFollow       bool   `json:"isFollow"`       // 当前登录用户是否已经关注了他
}

type UserUpdateReq struct {
	Avatar string `json:"avatar,optional"`
	Bio    string `json:"bio,optional"`
}

type UserUpdateResp struct {
}
