// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"miniblog/app/user/rpc/internal/logic/user"
	"miniblog/app/user/rpc/internal/svc"
	"miniblog/app/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *user.UserInfoRequest) (*user.UserInfoResponse, error) {
	l := userlogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *UserServer) UserUpdate(ctx context.Context, in *user.UserUpdateRequest) (*user.UserUpdateResponse, error) {
	l := userlogic.NewUserUpdateLogic(ctx, s.svcCtx)
	return l.UserUpdate(in)
}

// 【新增】批量查询 RPC 方法
func (s *UserServer) BatchGetUserInfo(ctx context.Context, in *user.BatchUserInfoReq) (*user.BatchUserInfoResp, error) {
	l := userlogic.NewBatchGetUserInfoLogic(ctx, s.svcCtx)
	return l.BatchGetUserInfo(in)
}
