// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: post.proto

package postclient

import (
	"context"

	"miniblog/app/post/rpc/post"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteRequest   = post.DeleteRequest
	DeleteResponse  = post.DeleteResponse
	DetailRequest   = post.DetailRequest
	DetailResponse  = post.DetailResponse
	ListRequest     = post.ListRequest
	ListResponse    = post.ListResponse
	PostItem        = post.PostItem
	PublishRequest  = post.PublishRequest
	PublishResponse = post.PublishResponse

	Post interface {
		Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
		// 内部获取列表的 RPC 方法
		List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
		// 新增：详情和删除 RPC 方法
		Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
		Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	}

	defaultPost struct {
		cli zrpc.Client
	}
)

func NewPost(cli zrpc.Client) Post {
	return &defaultPost{
		cli: cli,
	}
}

func (m *defaultPost) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

// 内部获取列表的 RPC 方法
func (m *defaultPost) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

// 新增：详情和删除 RPC 方法
func (m *defaultPost) Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.Detail(ctx, in, opts...)
}

func (m *defaultPost) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
