// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package interactionclient

import (
	"context"

	"miniblog/app/interaction/rpc/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentRequest  = interaction.CommentRequest
	CommentResponse = interaction.CommentResponse
	LikeRequest     = interaction.LikeRequest
	LikeResponse    = interaction.LikeResponse

	Interaction interface {
		// 点赞/取消点赞
		Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
		// 发表评论
		Comment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

// 点赞/取消点赞
func (m *defaultInteraction) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

// 发表评论
func (m *defaultInteraction) Comment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.Comment(ctx, in, opts...)
}
