// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommentDeleteReq struct {
	PostId    int64 `json:"post_id"` // 核心：分表路由键
	CommentId int64 `json:"comment_id"`
}

type CommentDeleteResp struct {
}

type CommentItem struct {
	Id            int64          `json:"id"`
	PostId        int64          `json:"post_id"`
	UserId        int64          `json:"user_id"`
	Username      string         `json:"username"`
	Avatar        string         `json:"avatar"`
	Content       string         `json:"content"`
	CreateTime    int64          `json:"create_time"`
	RootId        int64          `json:"root_id"`
	ParentId      int64          `json:"parent_id"`
	ReplyToUserId int64          `json:"reply_to_user_id"`
	ReplyToName   string         `json:"reply_to_name"`
	Children      []*CommentItem `json:"children"`
	ChildrenCount int64          `json:"children_count"`
}

type CommentListReq struct {
	PostId   int64 `json:"post_id"`
	Page     int64 `json:"page,optional"`
	PageSize int64 `json:"page_size,optional"`
}

type CommentListResp struct {
	List  []*CommentItem `json:"list"`
	Total int64          `json:"total"`
}

type CommentReq struct {
	PostId        int64  `json:"post_id"`
	Content       string `json:"content"`
	RootId        int64  `json:"root_id,optional"`
	ParentId      int64  `json:"parent_id,optional"`
	ReplyToUserId int64  `json:"reply_to_user_id,optional"`
}

type CommentResp struct {
	CommentId int64 `json:"comment_id"`
}

type LikeReq struct {
	PostId int64 `json:"post_id"`
}

type LikeResp struct {
}

type LikedListReq struct {
}

type LikedListResp struct {
	PostIds []int64 `json:"post_ids"`
}

type UnlikeReq struct {
	PostId int64 `json:"post_id"`
}

type UnlikeResp struct {
}
