// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommentReq struct {
	PostId  int64  `json:"post_id"`
	Content string `json:"content"`
}

type CommentResp struct {
	CommentId int64 `json:"comment_id"`
}

type LikeReq struct {
	PostId int64 `json:"post_id"`
}

type LikeResp struct {
}
