// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"miniblog/app/post/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取微型博客列表
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/post"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 发布微型博客
				Method:  http.MethodPost,
				Path:    "/publish",
				Handler: PublishHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/post"),
	)
}
